### ISSUE TITLE
simple:pg package missing

### ISSUE THREAD

**Issue by tamino-martinius** [meteor/postgres-packages#16]
It seems like this package doesn't exist anymore when i try to start the todos sample

``` sh
While selecting package versions:
error: unknown package in top-level dependencies: simple:pg
```

**Comment by tamino-martinius** [comment]
Just found them in the packages folder =/

**Comment by Slava** [comment]
yeah, because of the changes we made to the accounts package, right now the best way to use the packages is to load them in a local folder.

**Comment by yoonghm** [comment]
How do you **copy** the package `simple.pg` into my own meteor app?

**Comment by rclai** [comment]
Put all of [these folders](https://github.com/meteor/postgres-packages/tree/master/packages) into your meteor app's `packages` folder.

**Comment by yoonghm** [comment]
I had it fixed  by changing `PACKAGE_DIRS`. Thanks.
