### ISSUE TITLE
How to test?

### ISSUE THREAD

**Issue by robfallows** [meteor/postgres-packages#17]
So, I have a potential PR in the wings, but I realise there are no (Tinytest) tests and I am wondering how we tackle that, since a migration needs to be run in order to set up a new test database and tables. 

@stubailo: Have you given any thought to how unit testing might be done?

**Comment by Slava** [comment]
There are trivial tests for observe-driver. You can add more. https://github.com/meteor/postgres-packages/blob/master/packages/pg/observe-driver/tests.js

**Comment by robfallows** [comment]
Ah, cool! How did I miss those? Thank you :smile:
