### ISSUE TITLE
Publications are not sending any data

### ISSUE THREAD

**Issue by rclai** [meteor/postgres-packages#2]
The app right now in the current state doesn't publish anything now for some reason. There's no data in the client at all and the subscriptions are ready.

I did do a meteor shell query of the [join query](https://github.com/Slava/pg-example/blob/master/examples/react-todos/server/publish.js#L22-L32) on the list publication and appended `.run()` to it and saw that it returns data, but it looks like it's not able to publish the data.

I also tried to simplify the publishing query to just:

```
return Lists.knex().from("lists");
```

..with no luck.

**Comment by stubailo** [comment]
Yeah, right now there is something finicky - have you tried refreshing the app and dropping/creating the DB again?

We're working on making it more reliable soon, I think it has to do with connection pooling or something like that.

**Comment by rclai** [comment]
I just tried dropping, re-creating and re-migrating, but it still doesn't work. I'll chill for now.

**Comment by Slava** [comment]
We have rewritten the driver, let us know if you can still observe the issue. If so, please give us more details for the reproduction (version of PG, how you run it, what you see in PG logs, etc).

**Comment by rclai** [comment]
It works now! Good job on the refactorings!

**Comment by stubailo** [comment]
Woohoo!
