### ISSUE TITLE
unknown package in top-level dependencies: simple:pg

### ISSUE THREAD

**Issue by iuraya** [meteor/postgres-packages#28]
Hi,

I'm trying to build the targz of the react-todos to run it in a development server but while building the project I get the following error:

MacBook-Pro-de-Enrique:react-todos Kike$ meteor build ~/build-output-directory --server=*************
=> Errors while initializing project:         

While selecting package versions:
error: unknown package in top-level dependencies: simple:pg

It's also the same error I get if I try to update the project.

Thanks

**Comment by stubailo** [comment]
You need all of the environment variables here: https://github.com/meteor/postgres-packages/blob/master/examples/react-todos/run-app.sh

In particular, `PACKAGE_DIRS` is the one that tells Meteor where to find this package, since it's not published on Atmosphere.
