### ISSUE TITLE
Can't update from client

### ISSUE THREAD

**Issue by renato** [meteor/postgres-packages#59]
Hello,

Sorry if I'm missing something completely obvious, but I just can't use the Table.update() method from client. I was able to use a Meteor method but I'd like to know which methods are available client-side.

I got the `Uncaught Error: Not permitted. Untrusted code may only update documents by ID. [403]`.

Tried using: `Table.update(id, data).run();` and `Table.update(data).where({id: id}).run();`

Can I use it client-side or should I use a Meteor method instead?

Thanks!

**Comment by stubailo** [comment]
Only methods are supported in the current code.

**Comment by renato** [comment]
Thanks for the feedback!

I was using a method but decided to check the `Table.update` after seeing a `A method named '/table/update' is already defined` in the console.

**Comment by stubailo** [comment]
Ah yeah currently there isn't a way to stop meteor from defining that for every collection. I was hoping to remove that at some point but it didn't end up being a top priority.
