### ISSUE TITLE
Add the ability to do a static publication or subscription when steaming updates are not needed

### ISSUE THREAD

**Issue by ghost** [meteor/postgres-packages#8]
Maybe I missed it but I do not think so.

**Comment by stubailo** [comment]
@noah2828 Currently, this isn't a feature that Meteor publications have - they are always realtime. So this isn't really a Postgres-specific feature. Is there something about SQL that makes this feature more necessary than before?

**Comment by rclai** [comment]
You could use a method to return static data.

**Comment by queso** [comment]
Or put it in Meteor.settings and avoid the db calls.

**Comment by stubailo** [comment]
> Or put it in Meteor.settings and avoid the db calls.

What do you mean @queso?

**Comment by queso** [comment]
`Meteor.settings.staticData` could easily hold static data if needed.

**Comment by ghost** [comment]
Methods should work I was wondering if there was a different way of sending non reactive data with meteor sql implementation. As along as there is nothing preventing methods from doing it with the sql implementation. Than that answers my question thanks.
