### ISSUE TITLE
.fetchOne() and .fetchValue() support

### ISSUE THREAD

**Issue by rclai** [meteor/postgres-packages#9]
`.fetchOne()` is similar to Mongo's `.findOne()`. This would help to nicely wrap `.fetch()[0]` calls.

`.fetchValue()` would be used for one-off values like `COUNT` queries, or to just fetch the value of a single field in a row, which would help to safely wrap calls that do `.fetch()[0].field`. For example, `Todos.select('title').where({ id: 1 }).fetchValue()`.

**Comment by stubailo** [comment]
Hmm, sounds like a good idea! If we add a lot of stuff like this we probably need a real API doc for the query stuff. Right now the docs kind of punt it and say "look at the Knex docs".

**Comment by robfallows** [comment]
So, is the `help wanted` for the functionality or the API doc?

**Comment by stubailo** [comment]
Probably both! But the functionality is a much easier place to start :)

**Comment by robfallows** [comment]
Can this issue be closed now?
